### ISSUE TITLE
Windows support.

### ISSUE THREAD

**Issue by kierun** [svenstaro/pytest-colordots#2]
Is there any chance of windows support?…

**Comment by svenstaro** [comment]
Alright, I might just re-do this using [colorama](https://github.com/tartley/colorama).

**Comment by kierun** [comment]
☺ Thank you. I just had to use Windows and was missing this module.

**Comment by svenstaro** [comment]
This is now using colorama which should give us support across pretty much all OS! Considering this closed. A new version is available on PyPI.

**Comment by kierun** [comment]
Super. Many thanks indeed! ☺
